# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("accessibility.blockautorefresh", true);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1443736544);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1443736664);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1443736122);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1443736424);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1443736304);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.migration.version", 27);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 0);
user_pref("browser.search.countryCode", "IT");
user_pref("browser.search.region", "IT");
user_pref("browser.search.suggest.enabled", false);
user_pref("browser.search.useDBForOrder", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150922225347");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage", "http://search.frozenbox.org/pwn/");
user_pref("browser.syncPromoViewsLeftMap", "{\"addons\":2}");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"loop-button\",\"useragentoverrider-button\",\"noscript-tbb\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":4,\"newElementCount\":0}");
user_pref("capability.policy.maonoscript.sites", "addons.mozilla.org afx.ms ajax.aspnetcdn.com ajax.googleapis.com bootstrapcdn.com code.jquery.com firstdata.com firstdata.lv flashgot.net frozenbox.org gfx.ms informaction.com mozilla.net noscript.net parrotsec.org paypal.com paypalobjects.com persona.org securecode.com securesuite.net sfx.ms tinymce.cachefly.net wlxrs.com about: about:addons about:blank about:blocked about:certerror about:config about:crashes about:home about:memory about:neterror about:plugins about:preferences about:privatebrowsing about:sessionrestore about:srcdoc about:support blob: chrome: http://afx.ms http://bootstrapcdn.com http://firstdata.com http://firstdata.lv http://flashgot.net http://frozenbox.org http://gfx.ms http://informaction.com http://mozilla.net http://noscript.net http://parrotsec.org http://paypal.com http://paypalobjects.com http://persona.org http://securecode.com http://securesuite.net http://sfx.ms http://wlxrs.com https://afx.ms https://bootstrapcdn.com https://firstdata.com https://firstdata.lv https://flashgot.net https://frozenbox.org https://gfx.ms https://informaction.com https://mozilla.net https://noscript.net https://parrotsec.org https://paypal.com https://paypalobjects.com https://persona.org https://securecode.com https://securesuite.net https://sfx.ms https://wlxrs.com mediasource: moz-safe-about: resource:");
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"useragentoverrider@qixinglu.com\":{\"version\":\"0.2.5.1-signed\",\"type\":\"extension\",\"descriptor\":\"/home/eclipse/.mozilla/firefox/iNFubtGImosdf.Parrot/extensions/useragentoverrider@qixinglu.com.xpi\",\"multiprocessCompatible\":false}}");
user_pref("extensions.bprivacy.DataDir", "/home/eclipse/.macromedia");
user_pref("extensions.bprivacy.LSOcount", 2);
user_pref("extensions.bprivacy.initiated", 3);
user_pref("extensions.bprivacy.removed", 9);
user_pref("extensions.bprivacy.removedSession", 9);
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B73a6fe31-595d-460b-a920-fcc0f8843232%7D:2.6.9.37,%7Bd40f5e7b-d2cf-4856-b441-cc613eeffbe3%7D:1.68.1-signed,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:38.3.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1443736545);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "38.3.0");
user_pref("extensions.lastPlatformVersion", "38.3.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.useragentoverrider.activated", false);
user_pref("extensions.useragentoverrider.currentLabel", "");
user_pref("extensions.useragentoverrider.entries", "# Linux\nLinux / Firefox 26: Mozilla/5.0 (X11; Linux x86_64; rv:26.0) Gecko/20100101 Firefox/26.0\nLinux / Chrome 32: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.107 Safari/537.36\n\n# Mac\nMac / Firefox 26: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:26.0) Gecko/20100101 Firefox/26.0\nMac / Chrome 32: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.107 Safari/537.36\nMac / Safari 7: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_1) AppleWebKit/537.73.11 (KHTML, like Gecko) Version/7.0.1 Safari/537.73.11\n\n# Windows\nWindows / Firefox 26: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:26.0) Gecko/20100101 Firefox/26.0\nWindows / Chrome 32: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.107 Safari/537.36\nWindows / IE 6: Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)\nWindows / IE 7: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1)\nWindows / IE 8: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0)\nWindows / IE 9: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)\nWindows / IE 10: Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0)\nWindows / IE 11: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko\n\n# Android\nAndroid / Firefox 26: Mozilla/5.0 (Android; Mobile; rv:26.0) Gecko/26.0 Firefox/26.0\nAndroid / Chrome 32: Mozilla/5.0 (Linux; Android 4.4.2; Nexus 4 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.99 Mobile Safari/537.36\n\n# iOS\niOS / Chrome 32: Mozilla/5.0 (iPad; CPU OS 7_0_4 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) CriOS/32.0.1700.20 Mobile/11B554a Safari/9537.53\niOS / Safari 7: Mozilla/5.0 (iPad; CPU OS 7_0_4 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11B554a Safari/9537.53\n\n");
user_pref("extensions.useragentoverrider.firstRun", false);
user_pref("extensions.xpiState", "{\"app-profile\":{\"useragentoverrider@qixinglu.com\":{\"d\":\"/home/eclipse/.mozilla/firefox/iNFubtGImosdf.Parrot/extensions/useragentoverrider@qixinglu.com.xpi\",\"e\":true,\"v\":\"0.2.5.1-signed\",\"st\":1443736176000},\"{d40f5e7b-d2cf-4856-b441-cc613eeffbe3}\":{\"d\":\"/home/eclipse/.mozilla/firefox/iNFubtGImosdf.Parrot/extensions/{d40f5e7b-d2cf-4856-b441-cc613eeffbe3}.xpi\",\"e\":true,\"v\":\"1.68.1-signed\",\"st\":1443736183000},\"{73a6fe31-595d-460b-a920-fcc0f8843232}\":{\"d\":\"/home/eclipse/.mozilla/firefox/iNFubtGImosdf.Parrot/extensions/{73a6fe31-595d-460b-a920-fcc0f8843232}.xpi\",\"e\":true,\"v\":\"2.6.9.37\",\"st\":1443736001000}},\"app-global\":{\"{73a6fe31-595d-460b-a920-fcc0f8843232}\":{\"d\":\"/usr/lib/iceweasel/browser/extensions/{73a6fe31-595d-460b-a920-fcc0f8843232}.xpi\",\"e\":false,\"v\":\"2.6.8.22\",\"st\":1443736001000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/iceweasel/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"38.3.0\",\"st\":1443137816000,\"mt\":1442974055000},\"useragentoverrider@qixinglu.com\":{\"d\":\"/usr/lib/iceweasel/browser/extensions/useragentoverrider@qixinglu.com.xpi\",\"e\":false,\"v\":\"0.2.3\",\"st\":1443736176000},\"{d40f5e7b-d2cf-4856-b441-cc613eeffbe3}\":{\"d\":\"/usr/lib/iceweasel/browser/extensions/{d40f5e7b-d2cf-4856-b441-cc613eeffbe3}.xpi\",\"st\":1443736183000}}}");
user_pref("gecko.buildID", "20150922225347");
user_pref("gecko.mstone", "38.3.0");
user_pref("media.gmp-manager.buildID", "20150922225347");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("network.proxy.autoconfig_url", "file:///etc/tor/onion.pac");
user_pref("network.proxy.http", "127.0.0.1");
user_pref("network.proxy.http_port", 8080);
user_pref("network.proxy.share_proxy_settings", true);
user_pref("network.proxy.type", 2);
user_pref("noscript.ABE.migration", 1);
user_pref("noscript.autoReload.allTabs", false);
user_pref("noscript.global", true);
user_pref("noscript.gtemp", "");
user_pref("noscript.notify.hide", true);
user_pref("noscript.options.tabSelectedIndexes", "5,5,0");
user_pref("noscript.showDomain", true);
user_pref("noscript.showUntrustedPlaceholder", false);
user_pref("noscript.statusLabel", true);
user_pref("noscript.subscription.lastCheck", 805824561);
user_pref("noscript.temp", "");
user_pref("noscript.untrusted", "");
user_pref("noscript.version", "2.6.9.37");
user_pref("noscript.visibleUIChecked", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("pref.advanced.proxies.disable_button.reload", false);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("security.disable_button.openCertManager", false);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1443914825);
user_pref("toolkit.telemetry.previousBuildID", "20150922225347");
user_pref("ui.key.menuAccessKeyFocuses", false);
