configs/onion.pac /etc/anonsurf/
configs/torrc.base /etc/anonsurf/

cli/anonsurf /usr/bin/
bin/make-torrc /usr/lib/anonsurf/
bin/dnstool /usr/bin/

daemon/anondaemon /usr/lib/anonsurf/
sys-units/anonsurfd.service /lib/systemd/system/

launchers/anon-change-identity.desktop /usr/share/applications/
launchers/anon-surf-start.desktop /usr/share/applications/
launchers/anon-surf-stop.desktop /usr/share/applications/
launchers/anon-check-ip.desktop /usr/share/applications/