.TH AnonSurf
.SH Name
anonsurf \- Anonymizaton toolkit for Parrot Security OS
.SH Usage
AnonSurf [start | stop | restart | changeid | status | myip | dns]
.SH DESCRIPTION
.PP
Setup Tor proxy to route all traffic through Tor

* Modules:
  * UX: 
    * CLI (anonsurf): Handle user's options from command line interface.
    * GUI (anonsurf-gtk): A new friendly GTK GUI
  * Daemon: By now AnonSurf supports systemd only
    * anondaemon: A bash script to setup Tor transparent proxy
    * make_torrc: a simple script to handle configurations of session
  * Extra tool:
    * dnstool: Quick cli tool to change system DNS setting

* Features:
  * Start / stop / restart AnonSurf
  * Check current Tor status using Nyx
  * Change your ID by restarting to switch Tor nodes
  * Check your current public IP
  * Check if AnonSurf is enabled / disbled at boot
  * Enable / disable AnonSurf at boot (as system service)

* start:
  * Use bleachbit to kill dangerous applications (chrome skype thunderbird firefox...) 
  * Create system daemon starting Tor proxy gate
  * Disable IPv6 (security/IPv6 may reveal permanent MAC address)
  * Routes all internet packets/traffic through Tor
  * All DNS through Tor

* changeid:
  * Changes Tor node giving us new IP address using control port

* status:
  * Use Nyx application to display information about Tor service, bandwith, nodes...

* myip:
  * Check current IP address by checking response from Tor server

* status-boot: Show if AnonSurf is enabled / disabled
* enable-boot: Use systemctl (from systemd or 3rd package) to enable at boot
* disable-boot: Use systemctl (from systemd or 3rd package) to disable at boot

* dnstool:
  * Check current status: Dynamic / Static setting.
    * Dynamic: System use DCHP's settings
    * Static: Do not use DHCP's settings. Custom settings won't change after reboot
  * Set system DNS with Dynamic:
    * Use only DHCP server
    * Add more servers in tail (requires resolvconf). Extra servers won't change after reboot
  * Set Static DNS:
    * Repace DNS in /etc/resolv.conf
  * This tool supports OpenNIC servers by default.

.PP


.SH AUTHOR
Developed by:
 * Lorenzo "Palinuro" Faletra <palinuro@parrotsec.org>
 * Lisetta "Sheireen" Ferrero <sheireen@parrotsec.org>
 * Francesco "Mibofra" Bonanno <mibofra@parrotsec.org>

Maintained by:
 * Nong Hoang "DmKnght" Tu <dmknght@parrotsec.org>

.PP
This manual and package was written by Nong Hoang "DmKnght" Tu <dmknght@parrotsec.org> and RightToPrivacy <righttoprivacy@tutanota.com>
